# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Unittest

on:
  workflow_dispatch:
   inputs:
      environment:
        description: 'Environment to run tests against'
        default: sandbox
        type: choice
        options:
          - sandbox
          - prod
  push:
   branches: [ main ]
  pull_request:
   branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
         python-version: "3.10"
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
         pip install requests
         pip install ecdsa
         pip install parameterized

      - name: run testcase
        env:
            SECRET: "${{ github.event.inputs.environment == 'prod' && secrets.PRODSECRET || secrets.SANDBOXSECRET}}"
        run: python test.py --env ${{ github.event.inputs.environment }} --secret $SECRET


